/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 *
 * VaultIDV3 ABI stub — contract not yet deployed to mainnet.
 * Address is zero; all reads will return undefined and fail gracefully.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  8453: {
    VaultIDV3: {
      address: "0x0000000000000000000000000000000000000000" as `0x${string}`,
      abi: [
        // ERC721 base
        {
          inputs: [{ name: "tokenId", type: "uint256" }],
          name: "ownerOf",
          outputs: [{ name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [{ name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalMinted",
          outputs: [{ name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ name: "tokenId", type: "uint256" }],
          name: "tokenURI",
          outputs: [{ name: "", type: "string" }],
          stateMutability: "view",
          type: "function",
        },
        // Owner
        {
          inputs: [],
          name: "owner",
          outputs: [{ name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        // Pricing
        {
          inputs: [],
          name: "mintPriceCLAWD",
          outputs: [{ name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "mintPriceUSDC",
          outputs: [{ name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        // Vault data
        {
          inputs: [{ name: "tokenId", type: "uint256" }],
          name: "getVault",
          outputs: [
            {
              name: "",
              type: "tuple",
              components: [
                { name: "recoveryWallet", type: "address" },
                { name: "expiry", type: "uint256" },
                { name: "revoked", type: "bool" },
                { name: "credType", type: "uint8" },
                { name: "issuer", type: "address" },
                { name: "encryptedPayloadRef", type: "string" },
                { name: "metadataURI", type: "string" },
                { name: "schemaVersion", type: "uint256" },
              ],
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ name: "tokenId", type: "uint256" }],
          name: "isValidVault",
          outputs: [{ name: "", type: "bool" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { name: "tokenId", type: "uint256" },
            { name: "viewer", type: "address" },
          ],
          name: "isViewer",
          outputs: [{ name: "", type: "bool" }],
          stateMutability: "view",
          type: "function",
        },
        // Issuer registry
        {
          inputs: [{ name: "issuer", type: "address" }],
          name: "getIssuer",
          outputs: [
            {
              name: "",
              type: "tuple",
              components: [
                { name: "name", type: "string" },
                { name: "verified", type: "bool" },
                { name: "active", type: "bool" },
              ],
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        // Mint functions
        {
          inputs: [
            {
              name: "params",
              type: "tuple",
              components: [
                { name: "credType", type: "uint8" },
                { name: "issuer", type: "address" },
                { name: "encryptedPayloadRef", type: "string" },
                { name: "metadataURI", type: "string" },
                { name: "expiry", type: "uint256" },
                { name: "recoveryWallet", type: "address" },
                { name: "schemaVersion", type: "uint256" },
              ],
            },
          ],
          name: "mintWithCLAWD",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              name: "params",
              type: "tuple",
              components: [
                { name: "credType", type: "uint8" },
                { name: "issuer", type: "address" },
                { name: "encryptedPayloadRef", type: "string" },
                { name: "metadataURI", type: "string" },
                { name: "expiry", type: "uint256" },
                { name: "recoveryWallet", type: "address" },
                { name: "schemaVersion", type: "uint256" },
              ],
            },
          ],
          name: "mintWithUSDC",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        // Vault management
        {
          inputs: [{ name: "tokenId", type: "uint256" }],
          name: "revokeVault",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ name: "tokenId", type: "uint256" }],
          name: "unrevokeVault",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { name: "tokenId", type: "uint256" },
            { name: "newExpiry", type: "uint256" },
          ],
          name: "extendExpiry",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { name: "tokenId", type: "uint256" },
            { name: "wallet", type: "address" },
          ],
          name: "setRecoveryWallet",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ name: "tokenId", type: "uint256" }],
          name: "burnVault",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { name: "tokenId", type: "uint256" },
            { name: "viewer", type: "address" },
          ],
          name: "grantViewerPermission",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { name: "tokenId", type: "uint256" },
            { name: "viewer", type: "address" },
          ],
          name: "revokeViewerPermission",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { name: "tokenId", type: "uint256" },
            { name: "signer", type: "address" },
          ],
          name: "inviteSigner",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        // Owner admin functions
        {
          inputs: [
            { name: "clawd", type: "uint256" },
            { name: "usdc", type: "uint256" },
          ],
          name: "setMintPrices",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ name: "recipient", type: "address" }],
          name: "setFeeRecipient",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { name: "issuer", type: "address" },
            { name: "name", type: "string" },
          ],
          name: "registerIssuer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ name: "issuer", type: "address" }],
          name: "verifyIssuer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ name: "issuer", type: "address" }],
          name: "deactivateIssuer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ name: "issuer", type: "address" }],
          name: "reactivateIssuer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ] as const,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
